version: '3.8'

services: 

  nginx:
    image: nginx:1.28
    container_name: nginx
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
      - backend
      - frontend
    ports: 
      - "4001:80"
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.0-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql 
    restart: unless-stopped

  mysql:  
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - backend
    restart: unless-stopped

  phpmyadmin: 
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "6001:80"
    networks: 
      - backend
      - frontend
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  backend:
  frontend:
