version: '3.8'

services: 

  nginx:
    image: nginx:1.28
    container_name: nginx
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
      - backend
      - frontend
    ports: 
      - "4001:80"
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.0-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql 
    restart: unless-stopped

  mysql:  
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: db
      MYSQL_USER: ewa
      MYSQL_PASSWORD_FILE: run/secrets/mysql_password
    networks: 
      - backend
    restart: unless-stopped
    secrets:
      - mysql_root_password
      - mysql_password

  phpmyadmin: 
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ewa
      PMA_PASSWORD_FILE: /run/secrets/mysql_password
    networks: 
      - backend
      - frontend
    depends_on:
      - mysql
    restart: unless-stopped
    secrets:
      - mysql_password

volumes:
  mysql_data:

networks:
  backend:
  frontend:

secrets:
  mysql_root_password:
    file: mysql_root_password.txt
  mysql_password:
    file: mysql_password.txt